namespace Application.Errors;

public class GeneralApplicationErrorCodes
{
    public const string NOT_ALLOWED = "NOT_ALLOWED";
    public const string CANNOT_CREATE_ORDER = "CANNOT_CREATE_ORDER";
    public const string CANNOT_INVALID_PRODUCT_HISTORY = "CANNOT_INVALID_PRODUCT_HISTORY";
    public const string CANNOT_TOGGLE_NEW_PRODUCT_HISTORY = "CANNOT_TOGGLE_NEW_PRODUCT_HISTORY";
    public const string CANNOT_CREATE_INITIAL_PRODUCT_HISTORY = "CANNOT_CREATE_INITIAL_PRODUCT_HISTORY";
    public const string CANNOT_CREATE_DRAFT_IMAGE = "CANNOT_CREATE_DRAFT_IMAGE";
    public const string CANNOT_CREATE_ORDER_ITEM = "CANNOT_CREATE_ORDER_ITEM";
    public const string CANNOT_ADD_PRODUCT_IMAGE = "CANNOT_ADD_PRODUCT_IMAGE";
    public const string CANNOT_CREATE_PRODUCT = "CANNOT_CREATE_PRODUCT";
    public const string CANNOT_UPDATE_PRODUCT = "CANNOT_UPDATE_PRODUCT";
    public const string CANNOT_DELETE_PRODUCT = "CANNOT_DELETE_PRODUCT";
    public const string OPERATION_FAILED = "OPERATION_FAILED";
    public const string PRODUCT_DOES_NOT_EXIST = "PRODUCT_DOES_NOT_EXIST";
    public const string ORDER_DOES_NOT_EXIST = "ORDER_DOES_NOT_EXIST";
    public const string ORDER_ITEM_DOES_NOT_EXIST = "ORDER_ITEM_DOES_NOT_EXIST";
    public const string CANNOT_UPDATE_PRODUCT_IMAGES = "CANNOT_UPDATE_PRODUCT_IMAGES";
    public const string CANNOT_TRANSITION_ORDER_STATUS = "CANNOT_TRANSITION_ORDER_STATUS";
    public const string CANNOT_TRANSITION_ORDER_ITEM_STATUS = "CANNOT_TRANSITION_ORDER_ITEM_DATE";
    public const string PRODUCT_HISTORY_DOES_NOT_EXIST = "PRODUCT_HISTORY_DOES_NOT_EXIST";
}