services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - app-net

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - frontend-build:/app/react
        networks:
            - app-net
        environment:
            - NODE_ENV=production
        image: order-platform-microservice/frontend:latest

    file:
        build:
            context: ./fileServer
            dockerfile: Dockerfile
        volumes:
            - frontend-build:/app/static
            - uploaded-media:/app/media
        ports:
            - "3000:3000"
        networks:
            - app-net
        image: order-platform-microservice/file-server:latest

    proxy:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3100:3100"
        networks:
            - app-net
        depends_on:
            - redis
        environment:
            REDIS_URL: redis://redis:6379
        image: order-platform-microservice/proxy:latest

    auth:
        build:
            context: ./auth
            dockerfile: Dockerfile
        networks:
            - app-net
        ports:
            - "8000:8000"
        image: order-platform-microservice/auth-server:latest

    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:5000
        networks:
            - app-net
        image: order-platform-microservice/main-api:latest

networks:
    app-net:
        driver: bridge

volumes:
    uploaded-media:
    frontend-build:
